### ISSUE TITLE
Access-Control-Allow-Origin & ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by MunirajM** [DivanteLtd/open-loyalty#121]
Hi,

I have done the installation using Vagrant method and used only the below 4 commands and all went smooth without any issues,

```
vagrant up
vagrant ssh
docker-compose -f docker/docker-compose.yml up -d
docker-compose -f docker/docker-compose.yml exec php phing setup
```
I have adjusted the Vagrant file to use different port than its already available on the git. Also, I have updated the etc/hosts file with the below,

`127.0.0.1	openloyalty.localhost`

When I open the browser with the link http://openloyalty.localhost:8182, nothing opens and loader icon keeps spinning and seeing some errors on the console. Please find the below screenshot for the same,
https://prnt.sc/kflce6

Not sure where it needs to be adjusted further to make it work since everything fine with the **Quick install with Vagrant** commands.

Please help to complete the installation to make it work.

**Comment by elition31** [comment]
I got the same issue...

Did you solve your problem ?

**Comment by abhayjb** [comment]
Same issue! Is a quick fix available?

**Comment by Sharatheywa** [comment]
facing the same issue!!
Any help??

**Comment by colejarczyk** [comment]
Hi guys,

Have you tried follow the documentation https://open-loyalty.readthedocs.io/en/latest/cookbook/how_to_change_domain.html ?

As far as I know, when frontend application from one domain is trying to get data from another domain then Same Origin Policy is violated. To put it simply, either you have to ask for data from the same domain or ask from another with additional header "Access-Control-Allow-Origin" with value of domain from request came from or just "*" to accept all.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

So if you want to change domain, follow the documentation to configure Open Loyalty properly.

**Comment by colejarczyk** [comment]
@Sharatheywa @abhayjb @elition31 @MunirajM 

has my answer helped you? Do you have any more problems?

**Comment by colejarczyk** [comment]
due long time without response. this issue has been closed. If a problem still occurs, do not mind to reopen this issue.
